name: Build and Test Feature Branch
on:
  push:
    branches:
      - 'feature/*'
permissions:
  contents: read
  security-events: write
jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull and checkout for git repository
        run: |
          echo "pulling and checking out for git repository"
      - name: install npm packages
        run: npm install
      - name: install latest angular version
        run: npm install -g @angular/cli@latest
      - name: run test and build angular app
        run: |
          ng test --watch=false
          ng build --prod
          echo "run test and build angular app"
      - name: copy build to customer.back/src/main/resources/static folder
        run: |
          cp -R disti/customer-front/* ../customer-back/src/main/resources/static/
          echo "copy build to customer.back/src/main/resources/static folder"